name: Bug Report Form
description: File a bug report.
title: "[Bug]: "
projects: ["ctus-dev/5"]
type: "Bug"
assignees:
    - cubs818
body:
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
          value: "A bug happened!"
      validations:
          required: true
    - type: input
      id: needed-by
      attributes:
          label: Target Date
          description: Is this fix needed by a specific date or for a specific show?
          placeholder: YYYY-MM-DD
    - type: dropdown
      id: severity
      attributes:
          label: What is the severity of the bug?
          multiple: true
          options:
              - High
              - Medium
              - Low
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: shell
