name: Improvement Suggestion Form
description: Suggest an improvement.
projects: ["ctus-dev/5"]
type: "Task"
assignees:
    - cubs818
body:
    - type: textarea
      attributes:
          label: Suggestion
          description: How can we improve the project?.
      validations:
          required: true
