name: Task List
description: Generate a task list for the project
title: "Task List - "
projects: ["ctus-dev/5"]
type: "Task"

body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: "Detailed description of the task"
          placeholder: "Enter the task description"
      validations:
          required: true

    - type: input
      id: related_issues
      attributes:
          label: Related Issues
          description: "Links to related issues, if any"
          placeholder: "Enter related issue links"
